- name: Detectar nome e versão da distribuição
  ansible.builtin.debug:
    msg: "Distribuição: {{ ansible_distribution }} {{ ansible_distribution_release }} ({{ ansible_distribution_major_version }})"

- name: Remover o Zabbix Agent 1, se instalado
  ansible.builtin.package:
    name: zabbix-agent
    state: absent

- name: Adicionar repositório Zabbix para Debian/Ubuntu
  ansible.builtin.apt:
    deb: "https://repo.zabbix.com/zabbix/6.0/{{ ansible_distribution | lower }}/pool/main/z/zabbix-release/zabbix-release_6.0-4+{{ ansible_distribution_release }}_all.deb"
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Adicionar repositório Zabbix para RHEL/CentOS
  ansible.builtin.yum:
    name: "https://repo.zabbix.com/zabbix/6.0/rhel/{{ ansible_distribution_major_version }}/x86_64/zabbix-release-6.0-4.el{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  when: ansible_os_family == "RedHat"

- name: Atualizar cache dos pacotes (Debian)
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Instalar Zabbix Agent 2
  ansible.builtin.package:
    name: zabbix-agent2
    state: present

- name: Copiar configuração personalizada do Agent 2
  ansible.builtin.template:
    src: zabbix_agent2.conf.j2
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart Zabbix Agent 2

- name: Ativar e iniciar o serviço zabbix-agent2
  ansible.builtin.service:
    name: zabbix-agent2
    enabled: yes
    state: started
